# numpy crash course

In [1]:
import numpy as np

In [2]:
import sys
sys.version


'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [3]:
np.__version__

'1.26.4'

# creating list

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

# convert list to array

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [9]:
print(type(arr))
print(type(my_list))

<class 'numpy.ndarray'>
<class 'list'>


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
np.arange(10,50,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [16]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [17]:
np.arange(10,50,3,4)

TypeError: Cannot interpret '4' as a data type

In [18]:
np.arange(20,8)

array([], dtype=int32)

In [19]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(-20,8) #1st arg should less than 2nd arg always

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [21]:
n = np.arange(-20,8) #n is obj 
n

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [23]:
np.zeros(3)#parameter tunning-sys defined

array([0., 0., 0.])

In [24]:
np.zeros(3, dtype=int)#hyper parameter tunning-used defined

array([0, 0, 0])

In [25]:
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [27]:
z = np.zeros((5,3))#5x3 matrix
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [30]:
np.zeros((3,3), dtype=int)#int zero matrix

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
nd = np.zeros((5,9), dtype=int)
nd

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [35]:
nd = np.ones(3, dtype=int)
nd

array([1, 1, 1])

In [36]:
nd = np.ones((3,3), dtype=int)
nd

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [39]:
nd1 = np.ones((10,10), dtype=int)
nd1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [38]:
nd = np.three((10,10), dtype=int)#np can do only 1 and 0
nd

AttributeError: module 'numpy' has no attribute 'three'

In [ ]:
nd1